config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'
  get 'users/show'

  root 'users#new'

  get 'signup' 		=> 'users#new'
  get 'login' 		=> 'sessions#new'
  post 'login'		=> 'sessions#create'
  get 'actualuser' 	=> 'users#show'
  delete 'logout'	=> 'sessions#destroy'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	has_secure_password
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

	validates :name, presence: true, length: {maximum: 30}
	validates :email, presence: true, length: {maximum: 50}, format: {with: VALID_EMAIL_REGEX},
				uniqueness: {case_sensitive: false}
	validates :password, length: {minimum: 7}


	def User.digest(string)
	    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
	                                                  BCrypt::Engine.cost
	    BCrypt::Password.create(string, cost: cost)
	end

	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end
	
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email])
  	if user && user.authenticate(params[:session][:password])
  		log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
  		flash[:success] = "Estas dentro!!!"
  		redirect_to user
  	else
  		flash.now[:danger] = "Datos incorrectos"
  		render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  end

  def create
    @user = User.new(user_params)
  	if @user.save
      flash[:success] = "Bienvenido a hello!"
  		render 'new'
  	else
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	  def log_in(user)
  		session[:user_id] = user.id
  		session[:user_name] = user.name
  	end

    def remember(user)
      user.remember
      cookies.permanent.signed[:user_id] = user.id
      cookies.permanent[:remember_token] = user.remember_token
    end
    

  	def log_out
      forget(current_user)
  		session.delete(:user_id)
      session.delete(:user_name)
  		@current_user = nil
  	end

    def forget(user)
      user.forget
      cookies.delete(:user_id)
      cookies.delete(:remember_token)
    end

  	def current_user
      if(user_id = session[:user_id])
  		  @current_user ||= User.find_by(id: user_id)
      elsif(user_id = cookies.signed[:user_id])
        user = User.find_by(id: user_id)
        if user && user.authenticated?(cookies[:remember_token])
          log_in user
          @current_user = user
        end
      end
  	end

  	def logged_in?
  		!current_user.nil?
  	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<% provide(:name, "#{session[:user_name]}") %>
<header>
	<% if logged_in? %>
		<%= link_to "#{session[:user_name]}", actualuser_path %>
		<%= link_to "Log out", logout_path, method: "delete" %>
	<% else %>
		<%= link_to "Inicia sesion!",login_path %>
	<% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hello</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div> 
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1 id="titulo">Hello!</h1>
<h2 class = "subtitulo">Conecta con quienes quieran conectar contigo</h2>
<p class = "subtitulo" id = "instruccion">Solo tienes que registrarte para encontrar y ser encontrado :)</p>
<div class="formulario">
	<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>

	<%= f.label "Nombre", class: 'form-label'%>
	<%= f.text_field :name, class: 'form-control'%>

	<%= f.label :email, class: 'form-label'%>
	<%= f.email_field :email, class: 'form-control'%>

	<%= f.label "Contraseña", class: 'form-label'%>
	<%= f.password_field :password, class: 'form-control' %>

	<%= f.label "Repite tu contraseña", class: 'form-label'%>
	<%= f.password_field :password_confirmation, class: 'form-control'%>

	<%= f.submit "Crea mi cuenta!", class: "btn btn-primary"%>

	<% end %>

</div>

app/views/users/show.html.erb
<h1><%= session[:user_name]%></h1>